# Generated by Django 4.2.7 on 2024-02-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method_pay',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer_to_account', 'перевод на счёт')], max_length=100, verbose_name='способ оплаты'),
        ),
    ]
