# Generated by Django 4.2.7 on 2024-01-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.IntegerField(blank=True, null=True, verbose_name='превью'),
        ),
    ]
