# Generated by Django 4.2.7 on 2024-02-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_lesson_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ссылка на видео'),
        ),
    ]
